---

name: ((deployment_name))

instance_groups:
  - name: s3server
    instances: 1
    azs: [ z1 ]
    jobs:

      - name: create-buckets
        release: s3cmd
        properties: &buckets_properties
          buckets: [ ((bucket_name)) ]
          s3:
            host_base: ((s3server_endpoint_hostname))
            skip_ssl_validation: true
            access_key_id: ((scality_access_key_id))
            secret_access_key: ((scality_secret_access_key))

      - name: remove-buckets
        release: s3cmd
        properties: *buckets_properties

      - name: containers
        release: docker
        provides:
          s3server-address:
            aliases:
              - domain: ((s3server_endpoint_hostname))
                shared: false
        custom_provider_definitions:
          - name: s3server-address
            type: address
        properties:
          containers:
            - name: s3server
              image: scality/s3server:6018536a # tagged 'RC7.2.0-rc4' 'BETA7.2.0'
              store_dir: /var/vcap/store/s3server
              volumes:
                - /var/vcap/store/s3server/data:/usr/src/app/localData
                - /var/vcap/store/s3server/metadata:/usr/src/app/localMetadata
              bind_ports:
                - ((s3server_tcp_port)):8000
              env_vars:
                # See config vars usage in:
                # <https://github.com/scality/cloudserver/blob/BETA7.2.0/docker-entrypoint.sh>
                - SCALITY_ACCESS_KEY_ID=((scality_access_key_id))
                - SCALITY_SECRET_ACCESS_KEY=((scality_secret_access_key))
                - LOG_LEVEL=debug # can be 'info', 'debug', or 'trace'
                - SSL=true
                - ENDPOINT=((s3server_endpoint_hostname))
                - LISTEN_ADDR=0.0.0.0

      - name: docker
        release: docker

    persistent_disk_type: default
    vm_type: default
    stemcell: default
    networks:
      - name: ((network_name))

variables:
  - name: scality_secret_access_key
    type: password

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-60000

  max_in_flight: 1
  update_watch_time: 1000-60000

releases:
- name: s3cmd
  sha1: 7bd95458025073db6ddf922317676039a63268b0
  url: https://github.com/gstackio/s3cmd-boshrelease/releases/download/v1.1.0/s3cmd-1.1.0.tgz
  version: 1.1.0
- name: docker
  sha1: 8dcacf558067ed5302e30e4c8de928ee7917695e
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/docker-boshrelease?v=35.3.4
  version: 35.3.4
